# Generated by Django 3.0.3 on 2020-03-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='car_image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
