# Generated by Django 3.0.3 on 2020-03-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0002_carrent_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrent',
            name='costperkm',
        ),
        migrations.AddField(
            model_name='carrent',
            name='costperhr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carrent',
            name='fuel_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='carrent',
            name='transmission_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='carrent',
            name='car_driver',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrent',
            name='car_image',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
    ]
