# Generated by Django 3.0.3 on 2020-03-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0003_auto_20200315_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrent',
            name='car_image',
        ),
    ]
