# Generated by Django 3.0.3 on 2020-03-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0004_remove_carrent_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='car_color',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
