# Generated by Django 3.0.3 on 2020-03-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0005_carrent_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
