# Generated by Django 3.0.3 on 2020-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0006_auto_20200316_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='car_image',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
    ]
