# Generated by Django 3.0.3 on 2020-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0007_carrent_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrent',
            name='car_image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
