# Generated by Django 3.0.3 on 2020-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0008_auto_20200316_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrent',
            name='car_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
