# Generated by Django 3.0.3 on 2020-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0010_auto_20200316_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
