# Generated by Django 3.0.3 on 2020-03-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_new', '0012_auto_20200317_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='car',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_date', models.DateTimeField()),
                ('items', models.ManyToManyField(to='car_new.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
