# Generated by Django 3.0.3 on 2020-03-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0013_auto_20200317_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=250)),
                ('pickup', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
