# Generated by Django 3.0.3 on 2020-03-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0016_auto_20200319_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
