# Generated by Django 2.2.11 on 2020-03-29 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_new', '0017_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='car_num',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RentedCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('car_name', models.CharField(max_length=20)),
                ('username_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
