# Generated by Django 2.2.11 on 2020-03-29 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_new', '0018_auto_20200329_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentedCars',
            new_name='RentedCar',
        ),
    ]
