# Generated by Django 2.2.11 on 2020-03-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0019_auto_20200329_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrent',
            old_name='costperhr',
            new_name='costperday',
        ),
    ]
