# Generated by Django 2.2.11 on 2020-03-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0020_auto_20200329_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentedcar',
            old_name='car_name',
            new_name='car_num',
        ),
    ]
