# Generated by Django 3.0.3 on 2020-03-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_new', '0021_auto_20200329_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrent',
            name='car_driver',
        ),
    ]
